on:
  push:
    branches:
      - main
      - meysam/dev
  schedule:
    - cron: 0 0 * * *

env:
  JUPYTER_IMAGE_REPOSITORY: jupyter
  JUPYTER_IMAGE_TAG: latest
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          logout: false
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - name: Build Jupyter Notebook
        uses: docker/build-push-action@v2
        with:
          context: ./scripts/jupyter/
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.JUPYTER_IMAGE_REPOSITORY }}:${{ env.JUPYTER_IMAGE_TAG }}
