name: update-registry-index

on:
  push:
    branches:
      - main

env:
  HELM_VERSION: v3.11.2

jobs:
  update-registry-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm ${{ env.HELM_VERSION }}
        run: curl -fsSL https://git.io/get_helm.sh | bash
        env:
          DESIRED_VERSION: ${{ env.HELM_VERSION }}
      - name: Update chart packages
        run: |
          for chart in $(find charts/ -name Chart.yaml -exec dirname {} \;); do
            helm dep update $chart;
            helm package -d docs/ $chart;
          done
      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Update registry index
        run: helm repo index .
      - name: Commit and push changes
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Update registry index"
          git push origin gh-pages
